language: node_js

node_js:
    - "9.5.0"

branches:
    only:
        - master

before_install:
    - "npm install -g npm@6.3.0"

install:
    - npm i
    - npm install -g firebase-tools
    - npm install -g yarn

script:
    - yarn build

after_success:
    - firebase use prod
    - firebase deploy --token $FIREBASE_TOKEN

notifications:
    email:
        on_failure: change
        on_success: change
