/* eslint-disable max-len */
export const mockSourcedDB = {
  clubs: {
    '-KcK6EdiKmIMx8aHZRkf' : {
      'address' : {
        'city' : 'м. City',
        'country' : 'Україна',
        'line' : 'вул. Street, 12/2',
        'postCode' : '88000',
      },
      'email' : 'name.name@gmail.com',
      'fullNameEN' : 'Floorball Club \'Alfa\'',
      'fullNameUA' : 'Флорбольний клуб \'Альфа\'',
      'phone' : '+380990000000',
      'photo' : '-LEoEuWO_NtxQJeT_jzl',
      'shortNameEN' : 'FlC \'Alfa\'',
      'shortNameUA' : 'ФЛК \'Альфа\'',
      'url' : '',
    },
    '-KcT2q1Fud4fVXT9DFb0' : {
      'address' : {
        'city' : 'м. Київ',
        'country' : 'Ukraine',
        'line' : 'пр-т. Avenue, 18/18',
        'postCode' : '02000',
      },
      'email' : 's.syrkin@gmail.com',
      'fullNameEN' : 'Kyiv Floorball Club',
      'fullNameUA' : 'Київський флорбольний клуб',
      'phone' : '+38 097 804 91 17',
      'photo' : '-LEoEJI3V-paM6X2V73r',
      'shortNameEN' : 'KFC',
      'shortNameUA' : 'КФК',
      'url' : '',
    },
    '-Kd6Eq6cxdh_jOYRVI40' : {
      'address' : {
        'city' : 'м. Луцьк',
        'country' : 'Україна',
        'line' : 'вул. Станіславського, б. 15а, офіс 302',
        'postCode' : '43017',
      },
      'email' : 'icebergfimiam@gmail.com',
      'fullNameEN' : 'Sport Club \'Fimiam\'',
      'fullNameUA' : 'Громадська організація спортивний клуб \'Фіміам\'',
      'phone' : '+380954595123, +380501470808',
      'photo' : '-Kd6D_Hw2dJQN99w97rp',
      'shortNameEN' : 'SC \'Iceberg-Fimiam\'',
      'shortNameUA' : 'СК \'Айсберг-Фіміам\'',
      'url' : '',
    },
  },
  'counters' : {
    'playerID' : 1983,
  },
  'images' : {
    '-Kd6D_Hw2dJQN99w97rp' : {
      'downloadURL' : 'Some str with url',
      'fileName' : 'some file name',
      'lastModified' : 1487169999000,
      'md5Hash' : 'asjdkhkajsdhkjhasd',
      'size' : 68928,
      'tags' : [ 'iceberg' ],
      'type' : 'image/jpeg',
    },
    '-Kd6KvDSeCufk3S2Cr8c' : {
      'downloadURL' : 'Some str with url',
      'fileName' : 'Name.jpg',
      'lastModified' : 1487170002000,
      'md5Hash' : 'qS284P1ktF4EPJVUT+s7OQ==',
      'size' : 80912,
      'tags' : [ 'iceberg' ],
      'type' : 'image/jpeg',
    },
    '-Kd6LWowEBvgUz3v_xaK' : {
      'downloadURL' : '',
      'fileName' : 'Some Name.jpg',
      'lastModified' : 1487170038000,
      'md5Hash' : 'rl5INeorusR7cg7auEH+XA==',
      'size' : 164659,
      'tags' : [ 'iceberg' ],
      'type' : 'image/jpeg',
    },
  },
  'players' : {
    '-KcK2IJezJYk0PBp1Emb' : {
      'born' : 892846800000,
      'citizenship' : 'UA',
      'club' : '-KcK6EdiKmIMx8aHZRkf',
      'endActivationDate' : 1656540000000,
      'firstNameEN' : '',
      'firstNameUA' : 'Name',
      'gender' : 'MALE',
      'height' : '190',
      'lastNameEN' : '',
      'lastNameUA' : 'SecondName',
      'license' : '00000001',
      'licenseType' : 'Adult_A',
      'photo' : '-M0Pg_hdrQ6wnTA1R5C5',
      'position' : 'FORWARD',
      'registrDate' : 1486245600000,
      'secondNameUA' : 'NoNoName',
      'side' : 'L',
      'taxnumber' : '1231231231',
      'weight' : '79',
    },
    '-KcK9LR_sUzoeRrsGXog' : {
      'born' : 904424400000,
      'citizenship' : 'UA',
      'club' : '-KcK6EdiKmIMx8aHZRkf',
      'endActivationDate' : 1625004000000,
      'firstNameEN' : '',
      'firstNameUA' : 'Name',
      'gender' : 'FEMALE',
      'height' : '173',
      'lastNameEN' : '',
      'lastNameUA' : 'NameName',
      'license' : '00000002',
      'licenseType' : 'SENIOR',
      'photo' : '-M0PgG6PQ4IluBHVA9-Q',
      'position' : 'FORWARD',
      'registrDate' : 1486245600000,
      'secondNameUA' : 'MiddleName',
      'side' : 'R',
      'taxnumber' : '1231231231',
      'weight' : '55',
    },
    '-KcK9weojysunHgH_zDB' : {
      'born' : 981496800000,
      'citizenship' : 'UA',
      'club' : '-KcK6EdiKmIMx8aHZRkf',
      'endActivationDate' : 1535673600000,
      'firstNameEN' : '',
      'firstNameUA' : 'Name',
      'gender' : 'MALE',
      'height' : '60',
      'lastNameEN' : '',
      'lastNameUA' : 'NoName',
      'license' : '00000003',
      'licenseType' : 'JUNIOR',
      'photo' : '-KwjTJrxWBWMUCpxCnQg',
      'position' : '',
      'registrDate' : 1486245600000,
      'secondNameUA' : 'MiddleName',
      'side' : 'R',
      'weight' : '178',
    },
  },
  'transfers' : {
    '-Ks-XumSikWeGgKqPbo9' : {
      'date' : 1485907200000,
      'endDate' : 1496188800000,
      'fromClub' : '-KcT2q1Fud4fVXT9DFb0',
      'player' : '-KcK2IJezJYk0PBp1Emb',
      'toClub' : '-KeKyexHWx6jVyOH2VU1',
    },
    '-Ks-ZA-y2SGHjBzeEhKn' : {
      'date' : 1495929600000,
      'fromClub' : '-Kd_phRaSKZ31Nrvx8Ov',
      'player' : '-Kda00DPfimK6_Y23aW3',
      'toClub' : '-Ks-YZkNyoNFYRgLGz7O',
    },
    '-Ks-ZNUQpzbs4KVp1vFF' : {
      'date' : 1495929600000,
      'fromClub' : '-Kd_phRaSKZ31Nrvx8Ov',
      'player' : '-Kda-lUbBEEgtGVhtWw7',
      'toClub' : '-Ks-YZkNyoNFYRgLGz7O',
    },
  },
  'users' : {
    '43sqWiFk9LUqYg6j930uCpZuaa83' : {
      'displayName' : 'Name Name',
      'email' : 'name.name@gmail.com',
      'photoURL' : 'someurlstring.com',
      'role' : 99,
    },
  },
};
